// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileFilled from '/Users/zhangsen/Desktop/workcode/laifaxin-web/node_modules/.pnpm/@ant-design+icons@4.7.0_zpnidt7m3osuk7shl3s4oenomq/node_modules/@ant-design/icons/es/icons/SmileFilled';
import LikeFilled from '/Users/zhangsen/Desktop/workcode/laifaxin-web/node_modules/.pnpm/@ant-design+icons@4.7.0_zpnidt7m3osuk7shl3s4oenomq/node_modules/@ant-design/icons/es/icons/LikeFilled';
import PlusCircleFilled from '/Users/zhangsen/Desktop/workcode/laifaxin-web/node_modules/.pnpm/@ant-design+icons@4.7.0_zpnidt7m3osuk7shl3s4oenomq/node_modules/@ant-design/icons/es/icons/PlusCircleFilled';
import ContactsFilled from '/Users/zhangsen/Desktop/workcode/laifaxin-web/node_modules/.pnpm/@ant-design+icons@4.7.0_zpnidt7m3osuk7shl3s4oenomq/node_modules/@ant-design/icons/es/icons/ContactsFilled';
import DribbbleCircleFilled from '/Users/zhangsen/Desktop/workcode/laifaxin-web/node_modules/.pnpm/@ant-design+icons@4.7.0_zpnidt7m3osuk7shl3s4oenomq/node_modules/@ant-design/icons/es/icons/DribbbleCircleFilled';
import DashboardFilled from '/Users/zhangsen/Desktop/workcode/laifaxin-web/node_modules/.pnpm/@ant-design+icons@4.7.0_zpnidt7m3osuk7shl3s4oenomq/node_modules/@ant-design/icons/es/icons/DashboardFilled';
import PayCircleFilled from '/Users/zhangsen/Desktop/workcode/laifaxin-web/node_modules/.pnpm/@ant-design+icons@4.7.0_zpnidt7m3osuk7shl3s4oenomq/node_modules/@ant-design/icons/es/icons/PayCircleFilled';
import BellOutlined from '/Users/zhangsen/Desktop/workcode/laifaxin-web/node_modules/.pnpm/@ant-design+icons@4.7.0_zpnidt7m3osuk7shl3s4oenomq/node_modules/@ant-design/icons/es/icons/BellOutlined';
import HomeFilled from '/Users/zhangsen/Desktop/workcode/laifaxin-web/node_modules/.pnpm/@ant-design+icons@4.7.0_zpnidt7m3osuk7shl3s4oenomq/node_modules/@ant-design/icons/es/icons/HomeFilled';
import SettingFilled from '/Users/zhangsen/Desktop/workcode/laifaxin-web/node_modules/.pnpm/@ant-design+icons@4.7.0_zpnidt7m3osuk7shl3s4oenomq/node_modules/@ant-design/icons/es/icons/SettingFilled';
import MailOutlined from '/Users/zhangsen/Desktop/workcode/laifaxin-web/node_modules/.pnpm/@ant-design+icons@4.7.0_zpnidt7m3osuk7shl3s4oenomq/node_modules/@ant-design/icons/es/icons/MailOutlined';
import SettingOutlined from '/Users/zhangsen/Desktop/workcode/laifaxin-web/node_modules/.pnpm/@ant-design+icons@4.7.0_zpnidt7m3osuk7shl3s4oenomq/node_modules/@ant-design/icons/es/icons/SettingOutlined';
export default { SmileFilled, LikeFilled, PlusCircleFilled, ContactsFilled, DribbbleCircleFilled, DashboardFilled, PayCircleFilled, BellOutlined, HomeFilled, SettingFilled, MailOutlined, SettingOutlined };
