// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_3 from '/Users/zhangsen/Desktop/workcode/laifaxin-web/src/.umi/plugin-initialState/@@initialState';
import model_1 from '/Users/zhangsen/Desktop/workcode/laifaxin-web/src/models/themeMode';
import model_2 from '/Users/zhangsen/Desktop/workcode/laifaxin-web/src/models/user';

export const models = {
model_3: { namespace: '@@initialState', model: model_3 },
model_1: { namespace: 'themeMode', model: model_1 },
model_2: { namespace: 'user', model: model_2 },
} as const
