export const fieldOptions: any = {
  text: [
    { key: 'include', name: '包含(可多选)' },
    { key: 'exclude', name: '不包含(可多选)' },
    { key: 'eq', name: '是(单选)' },
    { key: 'neq', name: '不是(单选)' },
    { key: 'beginWith', name: '开头是(可多选)' },
    { key: 'beginNotWith', name: '开头不是(可多选)' },
    { key: 'endWith', name: '结尾是(可多选)' },
    { key: 'endNotWith', name: '结尾不是(可多选)' },
    { key: 'regexp', name: '正则表达式(高级语法)' },
    { key: 'notNull', name: '不为空' },
    { key: 'null', name: '为空' },
  ],
  textarea: [
    { key: 'include', name: '包含(可多选)' },
    { key: 'exclude', name: '不包含(可多选)' },
    { key: 'eq', name: '是(单选)' },
    { key: 'neq', name: '不是(单选)' },
    { key: 'beginWith', name: '开头是(可多选)' },
    { key: 'beginNotWith', name: '开头不是(可多选)' },
    { key: 'endWith', name: '结尾是(可多选)' },
    { key: 'endNotWith', name: '结尾不是(可多选)' },
    { key: 'regexp', name: '正则表达式(高级语法)' },
    { key: 'notNull', name: '不为空' },
    { key: 'null', name: '为空' },
  ],
  digit: [
    { key: 'eq', name: '等于' },
    { key: 'neq', name: '不等于' },
    { key: 'gte', name: '大于等于' },
    { key: 'lte', name: '小于等于' },
    { key: 'gt', name: '大于' },
    { key: 'lt', name: '小于' },
    { key: 'notNull', name: '不为空' },
    { key: 'null', name: '为空' },
  ],
  money: [
    { key: 'eq', name: '等于' },
    { key: 'neq', name: '不等于' },
    { key: 'gte', name: '大于等于' },
    { key: 'lte', name: '小于等于' },
    { key: 'gt', name: '大于' },
    { key: 'lt', name: '小于' },
    { key: 'notNull', name: '不为空' },
    { key: 'null', name: '为空' },
  ],
  percent: [
    { key: 'eq', name: '等于' },
    { key: 'neq', name: '不等于' },
    { key: 'gte', name: '大于等于' },
    { key: 'lte', name: '小于等于' },
    { key: 'gt', name: '大于' },
    { key: 'lt', name: '小于' },
    { key: 'notNull', name: '不为空' },
    { key: 'null', name: '为空' },
  ],
  select: [
    { key: 'include', name: '任意包含' },
    { key: 'exclude', name: '不包含' },
    { key: 'all', name: '同时包含' },
    { key: 'eq', name: '等于' },
    { key: 'notNull', name: '不为空' },
    { key: 'null', name: '为空' },
  ],
  date: [
    { key: 'lt', name: '早于 (哪一天)' },
    { key: 'gt', name: '晚于 (哪一天)' },
    { key: 'before', name: '在 (N天前)' },
    { key: 'after', name: '在 (N天内)' },
    { key: 'eq', name: '是 (哪一天)' },
    { key: 'neq', name: '不是 (哪一天)' },
    { key: 'notNull', name: '不为空' },
    { key: 'null', name: '为空' },
  ],
  dateTime: [
    { key: 'lt', name: '早于 (哪一天)' },
    { key: 'gt', name: '晚于 (哪一天)' },
    { key: 'before', name: '在 (N天前)' },
    { key: 'after', name: '在 (N天内)' },
    { key: 'eq', name: '是 (哪一天)' },
    { key: 'neq', name: '不是 (哪一天)' },
    { key: 'notNull', name: '不为空' },
    { key: 'null', name: '为空' },
  ],
};

export const MultiValuesList = [
  'all',
  'include',
  'exclude',
  'beginWith',
  'beginNotWith',
  'endWith',
  'endNotWith',
  'regexp',
];
