export const ImportExampleColumns = [
  {
    title: '编号',
    key: 'id',
    dataIndex: 'id',
  },
  {
    title: '姓名',
    key: 'name',
    dataIndex: 'name',
  },
  {
    title: '性别',
    key: 'gender',
    dataIndex: 'gender',
  },
  {
    title: '公司',
    key: 'company',
    dataIndex: 'company',
    width: 'auto',
  },
  {
    title: '部门',
    key: 'department',
    dataIndex: 'department',
  },
  {
    title: '邮箱',
    key: 'email',
    dataIndex: 'email',
  },
  {
    title: '手机号',
    key: 'mobile',
    dataIndex: 'mobile',
  },
];

export const ImportExampleData = [
  {
    id: 1,
    name: '雨泽',
    gender: '男',
    company: '来发信网络科技有限公司',
    department: '销售部',
    email: 'yuze@laifaxin.com',
    mobile: '13500000001',
  },
  {
    id: 2,
    name: '浩宇',
    gender: '男',
    company: '来发信网络科技有限公司',
    department: '销售部',
    email: 'haoyu@laifaxin.com',
    mobile: '13500000002',
  },
  {
    id: 3,
    name: '安娜',
    gender: '女',
    company: '来发信网络科技有限公司',
    department: '设计部',
    email: 'anna@laifaxin.com',
    mobile: '13500000003',
  },
  {
    id: 4,
    name: '瑞涛',
    gender: '男',
    company: '来发信网络科技有限公司',
    department: '项目部',
    email: 'ruitao@laifaxin.com',
    mobile: '13500000004',
  },
  {
    id: 5,
    name: '可馨',
    gender: '女',
    company: '来发信网络科技有限公司',
    department: '产品部',
    email: 'kexin@laifaxin.com',
    mobile: '13500000005',
  },
  {
    id: 6,
    name: '欣怡',
    gender: '女',
    company: '来发信网络科技有限公司',
    department: '销售部',
    email: 'xinyi@laifaxin.com',
    mobile: '13500000006',
  },
  {
    id: 7,
    name: '浩然',
    gender: '男',
    company: '来发信网络科技有限公司',
    department: '产品部',
    email: 'haorao@laifaxin.com',
    mobile: '13500000007',
  },
];
